# Site settings
title: blasterbug.github.io
#email: benjamin.sientzoff@yahoo.fr
description: Benjamin's corner on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blasterbug.github.io" # the base hostname & protocol for your site

github_username: blasterbug

# Handling Reading
encoding: "utf-8"

# Plugins
gem: ""

# Conversion
markdown:    redcarpet
redcarpet:
  extensions:
      - footnotes
      - hard_wrap
      - no_intra_emphasis
      - autolink
      - strikethrough
lsi:         true
excerpt_separator: "\n\n"

# GitHub Flavored Makdown
highlighter: pygments

# Configuration settings
timezone: Europe/Paris

# Outputting
permalink: /:year/:month/:title/
paginate: 10
paginate_path: /page:num


defaults:
  values:
    layout: "post"
    author: "Benjamin Sientzoff"

