title: blasterbug.github.io
description: Benjamin's corner on the web.
github_username: blasterbug
social:
  name: Benjamin Sientzoff
  links:
    - https://www.linkedin.com/in/benjaminsientzoff
    - https://github.com/blasterbug
    - http://stackoverflow.com/cv/blasterbug
# Handling Reading
encoding: "utf-8"
# Configuration settings
timezone: Europe/Paris
# Plugins
gems:
  - github-pages
  - jekyll
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap
  - kramdown

markdown: kramdown

defaults:
  -
    values:
      author: "Benjamin Sientzoff"
      layout: default
