# Site settings
title: blasterbug.github.io
#email: benjamin.sientzoff@yahoo.fr
description: >
 Site personnel de Benjamin Sientzoff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blasterbug.github.io" # the base hostname & protocol for your site

github_username: blasterbug

# Handling Reading
encoding: "utf-8"

# Plugins
gem: ""

# Conversion
markdown:    kramdown
lsi:         true
excerpt_separator: "\n\n"

# Configuration settings
timezone: Europe/Paris

# Outputting
permalink: /:year/:month/:title/
paginate: 10
paginate_path: /page:num


defaults:
  values:
    layout: "post"
    author: "Benjamin Sientzoff"

