
# Site settings
title: blasterbug.github.io
#email: blasterbug@users.noreply.github.com
description: Benjamin's corner on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blasterbug.github.io" # the base hostname & protocol for your site

github_username: blasterbug

# Handling Reading
encoding: "utf-8"

# Plugins
gems:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap

# Conversion
markdown: kramdown

kramdown:
  # GitHub Flavored Makdown
  input: GFM
  syntax_highlighter: rouge
  extensions:
    - footnotes
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough

lsi: true

excerpt_separator: "\n\n"

# Configuration settings
timezone: Europe/Paris

# Outputting
permalink: /:year/:month/:title/
paginate: 10
paginate_path: /page:num

defaults:
  -
    values:
      author: "Benjamin Sientzoff"
      code: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
